const express=require("express");
const cors=require("cors");
const app=express();
const authRoutes=require('./routes/AuthRoutes');
const startupRoutes=require('./routes/StartupRoutes');
const investorRoutes=require('./routes/investorRoutes');
const adminRoutes=require('./routes/adminRoutes');
const dashboardRoutes=require('./routes/dashboardRoutes');
const mentorRoutes = require("./routes/mentorRoutes");
app.use(cors());
app.use(express.json());
app.use('/api/auth',authRoutes);
app.use('/api/startups', startupRoutes);
app.use('/api/investors', investorRoutes);
app.use('/api/admin', adminRoutes);
app.use('/api/dashboard', dashboardRoutes);
app.use("/api/mentor", mentorRoutes);
app.get('/',(req,res)=>{
    res.send("Server is running ");
});
module.exports=app;